[[ICU]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "275c778b25794c0aa41278f09f8cc7d47b03376b"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "eb22e95b9c64fc688b16191c3a6279136643c1c217fb3811fd672c9f93bfa15f"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+3/ICU.v67.1.0.aarch64-linux-gnu-cxx03.tar.gz"
[[ICU]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e1965ed72307e8769fe2fd71436c75545f6c405b"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "3452b01d6c2e901e4b1578ae5c8b14989bee2ba9be9f33185024e33609791915"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+3/ICU.v67.1.0.aarch64-linux-gnu-cxx11.tar.gz"
[[ICU]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9aac0c19503f7755a65ad8b9d6a07857eff599d0"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "334fa2f9dcb1b2a0fcd3a9efde5156d4a100906584bdc9689853b14867fe4333"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+3/ICU.v67.1.0.aarch64-linux-musl-cxx03.tar.gz"
[[ICU]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9fa55a0d1bc5e8dbfd64ebdae1293da793495e17"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "d5eebc43c35c608ef14862288b31ba7de86e8a86a6305408aa437a6f48fd0f37"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+3/ICU.v67.1.0.aarch64-linux-musl-cxx11.tar.gz"
[[ICU]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "daf6368abe9ff0a538afe50d4d134bd20a34137d"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "b3529e761b45b0fc9e1f92bb492a79821482d8100573520496d9a03d20368c54"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+3/ICU.v67.1.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ICU]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d8ea1b334209520d05ea13b4ecfc64566a6ab60a"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "f68cf908c8856359c005712673126cfcae29d2c89950e86fe76d0d19adf25f69"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+3/ICU.v67.1.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ICU]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f0210e50f0cce547e32689b43621abd1f47bb18b"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "25dcc4e59ab301e9ecbc43eb97d111fc4fe0cf8c6536b9685edfad1815184d0d"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+3/ICU.v67.1.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ICU]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "87d4c20b48ffbdcf4993ff33fc6587108194a177"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "89ab5a54f5c4a2beb8a1ff85df9501e1427342b3efd088164dcb2441b9080f91"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+3/ICU.v67.1.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ICU]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "068762db00e2da0444ae2c6f998d46226678d689"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "539b44503540f05363fe080fffd4e869ed0b694eb4d6d2d30de046975ec01035"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+3/ICU.v67.1.0.i686-linux-gnu-cxx03.tar.gz"
[[ICU]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a0cf18fb382e40c6b6780c9f9b279d81cf209f4a"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "fc8748bce04af6df82abcf972debf61db9d243528c782c0dfd1d946aa753029a"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+3/ICU.v67.1.0.i686-linux-gnu-cxx11.tar.gz"
[[ICU]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "760cf61d6d0fa875f25634cb6ab76df3d162216c"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "78feaab64f151f2719761bb54149999060d91f7e14ae8ba383ca6c18d40d169b"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+3/ICU.v67.1.0.i686-linux-musl-cxx03.tar.gz"
[[ICU]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a80fc29a34e7d5519837d536e57412c9762d99e0"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "9db7088a81e4392a61d26426107258bbf1370de03f52252ffa4c8dd986f02aeb"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+3/ICU.v67.1.0.i686-linux-musl-cxx11.tar.gz"
[[ICU]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef37820248c58cce2d154f39a4c0d45a578ddee7"
os = "windows"

    [[ICU.download]]
    sha256 = "1fd3f9bfec9d3796a6fe8cbd88495f4bf6eb8769de0edd04cc2abea9ae5a3303"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+3/ICU.v67.1.0.i686-w64-mingw32-cxx03.tar.gz"
[[ICU]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "637022053ec7a47a918b5a0108861bdc75f9d4f5"
os = "windows"

    [[ICU.download]]
    sha256 = "ac9e7e0b702c995af83ab012ae11f67c9e94b5d780dd35b4086f8ab558696ad3"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+3/ICU.v67.1.0.i686-w64-mingw32-cxx11.tar.gz"
[[ICU]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a7784c50967894c15b25e271399ddc34303b0942"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "451246e49256b18de41b3b719a583020c62c59a7f65fafb03f9d1a5fc0d5d40e"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+3/ICU.v67.1.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[ICU]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0dcb11ee724b075fd77f8bb7c122852147d0281c"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "79f91a2919294173e4c84b7065b243aa680d79e1506bb00fd30fbd884708deab"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+3/ICU.v67.1.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ICU]]
arch = "x86_64"
git-tree-sha1 = "14819d58d81af1286ea71ca9ab144f64bb41f625"
os = "macos"

    [[ICU.download]]
    sha256 = "a9c06217039f5914b2c80821b481f05f7c9f4170d2e7e33da27cc5b0c079e0b4"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+3/ICU.v67.1.0.x86_64-apple-darwin.tar.gz"
[[ICU]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6ddbcbd60f3d40be36022822c355e0bf59540856"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "fa3dcfb00d99051f7287632f0ac687e86cd91e2a6dfa38cc8fe5e7df2aef71e9"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+3/ICU.v67.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[ICU]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "76b60565e02edacb1b13d24771099d813ecad6f9"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "4cdb2917afc1c585420e1b47d81e1f3a8c66465a68a659ba09810a9038d2f83e"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+3/ICU.v67.1.0.x86_64-linux-gnu-cxx11.tar.gz"
[[ICU]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4808be40883f11ee6312155f3823d26b0ee2fa78"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "99bafd9e1bbc98c2b09874fc70f3be847bcd18b246d16fd71503676bd3b60c32"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+3/ICU.v67.1.0.x86_64-linux-musl-cxx03.tar.gz"
[[ICU]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b538add0719dd6204bbfbf8a56648c892cdabf2"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "d3f213f7831238988afa6952956dfc90cab74f0cd5d4eaad79007c5e7211ddb7"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+3/ICU.v67.1.0.x86_64-linux-musl-cxx11.tar.gz"
[[ICU]]
arch = "x86_64"
git-tree-sha1 = "37c184a0a3a78f32b8e12b31308fad47e01559cd"
os = "freebsd"

    [[ICU.download]]
    sha256 = "b9e629fb140fbb2b0058b1eeaaa9a162e7113ff460932292f85c93292dff5c2d"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+3/ICU.v67.1.0.x86_64-unknown-freebsd.tar.gz"
[[ICU]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9ca4f903b971d762668d48c5fc49d61b0aa70418"
os = "windows"

    [[ICU.download]]
    sha256 = "862e8d9386b9f73fb44b6a93ea6d5d31706c345b4b3510af309ccc9421614d54"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+3/ICU.v67.1.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[ICU]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1e6075d26f5d0a8d32776b877b1da5ae43f664ba"
os = "windows"

    [[ICU.download]]
    sha256 = "79ed8565c646590fffe7361af2b2f3633b8518ec842c95d170bd087dca8b7fa9"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+3/ICU.v67.1.0.x86_64-w64-mingw32-cxx11.tar.gz"
