[[ICU]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "37fc89829d80b119d467a4b8dedef4866105ddbc"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "5a9bf800598d8cc9f6344c58cd0b0d721986e7bc0c25121877ec1710027a4267"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v68.2.0+0/ICU.v68.2.0.aarch64-linux-gnu-cxx03.tar.gz"
[[ICU]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "33cbfa8ba985fc74d06a16f14eb6baa50a1fff9b"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "81d84edbbfd03b915c0b3af4f1cfdebfa497e073a62b0b87ef76c76c812bec0a"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v68.2.0+0/ICU.v68.2.0.aarch64-linux-gnu-cxx11.tar.gz"
[[ICU]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef122379681e31d850023afc579f427feb3cf8c7"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "b735097ac7b17b87208ca499481fe447d4ffd6fe71be96d5a6a26df93d8527d5"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v68.2.0+0/ICU.v68.2.0.aarch64-linux-musl-cxx03.tar.gz"
[[ICU]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a5b1390df87e3ba86036bb2ed433810de6e56393"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "5e90cb9681165f0708d562cb7d19676dcabd8c54c793bb9cf29369f739c576ae"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v68.2.0+0/ICU.v68.2.0.aarch64-linux-musl-cxx11.tar.gz"
[[ICU]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3b272f9eb4e2b3ae2d0ae61494776e1e982c4a86"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "acf6f77a7fe2533ffa54964f8f247a5c4953905bc1ebf6adc1ab0bda56e119b7"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v68.2.0+0/ICU.v68.2.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ICU]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3eecf42fdbc2e65c372550d364c9d0c096d58f51"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "c321010c416fb22c393e614682bcdb516cfe94d874d8bf7484f692922ac3dedd"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v68.2.0+0/ICU.v68.2.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ICU]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7e2f8b2aa0b847347286ee0ad02fe307838db709"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "4a5ff91184a0a61e9d89b690ba111216c52f2dc219b7032894d591733b578bd7"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v68.2.0+0/ICU.v68.2.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ICU]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "25803df029437d7edf856375d0d83e8c0ff9be72"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "ce80be2b85c48dbf15af6fcf9a5a0c4a1b112391a49c9664c3fe1f496c0fa94e"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v68.2.0+0/ICU.v68.2.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ICU]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ce520ed526b89de3e86efab79584849d44de2a52"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "4c1d89b9e36c98c2678d7892cf4d4a5a36dd811b0cc4a2901368c06248e80d5e"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v68.2.0+0/ICU.v68.2.0.i686-linux-gnu-cxx03.tar.gz"
[[ICU]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f2efa34ba91759fc60b420b0b21e502ba838802"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "74e98a7fc55eca16a6ba7c2c30df55d5d1652e12aca98b2371a39c820801961d"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v68.2.0+0/ICU.v68.2.0.i686-linux-gnu-cxx11.tar.gz"
[[ICU]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0957a777194dac9b8be6947b3ddc652f21163d12"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "bf884ca9d87d4b9507ff3d08cf9e2bf083a20ccce91b700acb7c19b335e34e72"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v68.2.0+0/ICU.v68.2.0.i686-linux-musl-cxx03.tar.gz"
[[ICU]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "91333516d2911d6b1b73ad4c305414058f9328b5"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "d5dcc1e3050d35484c8cfc5e4efc51e011b86d113d73d2f06e7ef7ab9e217af4"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v68.2.0+0/ICU.v68.2.0.i686-linux-musl-cxx11.tar.gz"
[[ICU]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f868651bfb37baa63c5bd399f5b951dc49ee4004"
os = "windows"

    [[ICU.download]]
    sha256 = "f7ae0d0e2c1fec6e2d483b0a1faa1306a2ea4614ab3384044935581a091b2921"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v68.2.0+0/ICU.v68.2.0.i686-w64-mingw32-cxx03.tar.gz"
[[ICU]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d168fdd2b7bc1b327a55fa4e216129002a3aa4fe"
os = "windows"

    [[ICU.download]]
    sha256 = "48ed18375b82ae03a9fd7c71a7cf838a36a6d63e35744d49d705c8e3c8a2ce12"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v68.2.0+0/ICU.v68.2.0.i686-w64-mingw32-cxx11.tar.gz"
[[ICU]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "62181da64248a2b84ea5859e0f105a9c0d5923c3"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "344c292c6b52672bcdd34a70dc87188659f7e6526455bbcc02db5b4cc4b413da"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v68.2.0+0/ICU.v68.2.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[ICU]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "32d515921c69c4ffc2ff493d3e38f85476ee8a0b"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "e2bdddb6d4427a7bdce77e36c0b56470c8bd5a592f8d3533cbb2744b91c8469e"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v68.2.0+0/ICU.v68.2.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ICU]]
arch = "x86_64"
git-tree-sha1 = "ca0c337752fca30cbefb7d22898d2e294b7b5ecc"
os = "macos"

    [[ICU.download]]
    sha256 = "de48693933ed26f42d67423d1894e600e28378581deeca883c8d615bebe49a87"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v68.2.0+0/ICU.v68.2.0.x86_64-apple-darwin.tar.gz"
[[ICU]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9d4116620a2fff754ba6833eb3effb592dc6352a"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "0e8b5cd3fcc3d04956bfeb83a60969e0077f2e288c6b46adcc11487e96c7aed3"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v68.2.0+0/ICU.v68.2.0.x86_64-linux-gnu-cxx03.tar.gz"
[[ICU]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1cb68e90a5ad4655378340dd08ba2274bf5961c4"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "f804209c74006947d7f6ba4ba9fb632a1bf5cb1af7a8a486fbad615eddfbe62f"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v68.2.0+0/ICU.v68.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[ICU]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a17e70831bd8dd935f943083b98d2fe646c457c0"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "6d38aaf959ccadc42960c02f96e4c928823c4bbc8d6b91fc07ab62bbcc7fec68"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v68.2.0+0/ICU.v68.2.0.x86_64-linux-musl-cxx03.tar.gz"
[[ICU]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "baab6857f9e5aad9798777554a1044be47ce6b21"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "6903cd9ee2fa0277bdc0a85285d95ff5d929d861d23620d23e709c367c9a2973"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v68.2.0+0/ICU.v68.2.0.x86_64-linux-musl-cxx11.tar.gz"
[[ICU]]
arch = "x86_64"
git-tree-sha1 = "31465b626fdcd9c9b12b038a7a3614685e8611c5"
os = "freebsd"

    [[ICU.download]]
    sha256 = "f63a95c29912f91cceabbd75cd725dc3852377b226a0ef168c0f9d8253163dfa"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v68.2.0+0/ICU.v68.2.0.x86_64-unknown-freebsd.tar.gz"
[[ICU]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "76ac4ae78d74bf5970f795bc150a6ffa183e1916"
os = "windows"

    [[ICU.download]]
    sha256 = "a015038bac5c03e98e5e6ecbdc277c140406c0639b714d5e7e9fb822ad1e5dfb"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v68.2.0+0/ICU.v68.2.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[ICU]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6fa755a9d131d19dff925398388b6cc10d21f17d"
os = "windows"

    [[ICU.download]]
    sha256 = "c45eb8a04bbe7af3ecbc40dbc7729e91a8b5f96fe7639d2c9b79435104b36d5f"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v68.2.0+0/ICU.v68.2.0.x86_64-w64-mingw32-cxx11.tar.gz"
