[[ICU]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3042826394ce1c99f31520273b2518dd4674c8f4"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "e6a9b21300f3f81b8f8fa32eb97ed52d9915391bfc9a590d01c8385bbed88fb4"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+2/ICU.v67.1.0.aarch64-linux-gnu-cxx03.tar.gz"
[[ICU]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e356acafae688da390a57257b69ca5ccf1812214"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "532373f6a6256547de6e08c9232299d51be87a79e1c180bdefb8c4407affc451"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+2/ICU.v67.1.0.aarch64-linux-gnu-cxx11.tar.gz"
[[ICU]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "985de27739f709cb84bf49e96b28d5c8c7d2432b"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "bf7a0cdd57906005f8a74625c88bbe1d699d509536e6a22cdc30bb7fdb89abef"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+2/ICU.v67.1.0.aarch64-linux-musl-cxx03.tar.gz"
[[ICU]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b88fb83c1a3f0ea1ec3d1385c28f9760085e2900"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "c099eb24ea4719b194c97990378e4328890cb37a1f1ab86ffa687699d45d11be"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+2/ICU.v67.1.0.aarch64-linux-musl-cxx11.tar.gz"
[[ICU]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bfb5feb95f8ddb8aafa6066761b9436f0eac1d12"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "85eec7cadb9838829e79f5cf16926cb44582ab8de3ef56eeff8f8d3611f8ec65"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+2/ICU.v67.1.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ICU]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0d907e5a25e2c0f8e5cd128278fc625720c9525e"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "def9142639f76232384e9901603d3e044d6f86bdd3f72d57973d6ee212894316"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+2/ICU.v67.1.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ICU]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "73c8b2075f6dd1b86199383e2ebffc0b9547a0dc"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "f670aa7c80ec75c04ca5609569c8fd68a19b522e89fcb7aa53986874780cb19a"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+2/ICU.v67.1.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ICU]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "794e32a9a7ed99e13bc83ab358faaf5cc68bc563"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "b5111f272ea37f5a015323c5689faaf8816297948a321ad4d26b22590f011570"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+2/ICU.v67.1.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ICU]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "66a011f6aa1d7d7033a970103b4af75d312257c7"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "91b5cedab30b1d5e4617ab7d2844deb855fb1cf8ab1c75a98471ebca0ca6dbfc"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+2/ICU.v67.1.0.i686-linux-gnu-cxx03.tar.gz"
[[ICU]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "40b60ee49a2de06819dc79b544ab0733b329ccfb"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "45eb662a39c545a07d1c612fb516379d802088ffdccd6323f1477061aa7b5991"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+2/ICU.v67.1.0.i686-linux-gnu-cxx11.tar.gz"
[[ICU]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9772ed3ce7799dbb433c58e90fa0d85635272f43"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "03eb61f15ec16878b2f46207c3e5ae338a49044be0a076af2cf5305def399185"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+2/ICU.v67.1.0.i686-linux-musl-cxx03.tar.gz"
[[ICU]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8089421c490c22bb07bbfc787a2b08bd501eff68"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "f587b50f6524e7877fca73ad17037bb5aa5ebb01ed324387f0d75a579b13c79a"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+2/ICU.v67.1.0.i686-linux-musl-cxx11.tar.gz"
[[ICU]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2966a832b5d604c0caf9e2935eb5940a1c060984"
os = "windows"

    [[ICU.download]]
    sha256 = "314a4ba6c2c7dcf80438818d3ae02c16a2d4150490ebc68f3c6be8b67b27e149"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+2/ICU.v67.1.0.i686-w64-mingw32-cxx03.tar.gz"
[[ICU]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "894df975b81d312665928fa0ee37f94734f0a23b"
os = "windows"

    [[ICU.download]]
    sha256 = "8377aca46440961d9715c850967c1a8a8e76a7ba5da1854a3d573d9b53cdc8af"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+2/ICU.v67.1.0.i686-w64-mingw32-cxx11.tar.gz"
[[ICU]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0a5b13e561368c85fbe970507faa7ba136692c2c"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "5cef9b85bf84fea6a745dc7e784104db67c5116590505a90fcce1e3b6afb34dd"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+2/ICU.v67.1.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[ICU]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d787f65f725f7e3b2272b80618393ad0e2da385d"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "b76ff00437e489fe59ae9a6aa3e87591c5665b2e1f5d0eaf7e29ea6b5f2a3dc2"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+2/ICU.v67.1.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ICU]]
arch = "x86_64"
git-tree-sha1 = "cecc5d9174d113ce6a5a35798d26f54375402598"
os = "macos"

    [[ICU.download]]
    sha256 = "75415501626127461204f1c4326e30fc81685cbed2486d8c918fb55b99aaa673"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+2/ICU.v67.1.0.x86_64-apple-darwin.tar.gz"
[[ICU]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d297f3972bcf8b06b1ed4229d31977c969f29d44"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "554e365dae8f4b2d3cf28a48cce691b3e0eba294bbfdb0975f1c93d378a53b9b"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+2/ICU.v67.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[ICU]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cd96e2cc28d094410e47fbcb103eec64107c3cf1"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "f3f39360f058bfa6ded52b6c722986b7e7a1c68b42a992549fcc796bb9514646"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+2/ICU.v67.1.0.x86_64-linux-gnu-cxx11.tar.gz"
[[ICU]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3ee59901581f2fdc4387c259ae7a78863a90e7ff"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "d939bec8fb4026de8e39e1daf1b66ea741ed7896d4a7790e38a20513190865ef"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+2/ICU.v67.1.0.x86_64-linux-musl-cxx03.tar.gz"
[[ICU]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "70a893a91021985009e7d07b288aad47ef11d620"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "d1f8c080eba51b50da09c482822d005791afa87e433f8ced3d171436af4e139a"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+2/ICU.v67.1.0.x86_64-linux-musl-cxx11.tar.gz"
[[ICU]]
arch = "x86_64"
git-tree-sha1 = "29aea2a1d8a43b889ccd6d116d76a800b612b37a"
os = "freebsd"

    [[ICU.download]]
    sha256 = "86c50dff4e26b17b8cbb808c45de9a4f2be9ca643fa3802c8ac97410b9cbaa3b"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+2/ICU.v67.1.0.x86_64-unknown-freebsd.tar.gz"
[[ICU]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "992eb63da62c298ba6ac41795092ccf709776964"
os = "windows"

    [[ICU.download]]
    sha256 = "1afba81dba473c3c5e0be1cff9daf241b6d4b05401109b688367b70a1d060060"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+2/ICU.v67.1.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[ICU]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e8465fe516f7fe9987089c59f5b3e49562fdd1b3"
os = "windows"

    [[ICU.download]]
    sha256 = "c8501a248b308489bfcbe66dbe51518d7a35d0a2844a071c99f88f3677721a81"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+2/ICU.v67.1.0.x86_64-w64-mingw32-cxx11.tar.gz"
