[[ICU]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e3e767e37e78c8310f2a8c158ae5d9153cbbe0eb"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "6ef7add9c031a1d2dac17d0869b480e9ac2973402a4047da75f59b275afbd7b9"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+0/ICU.v67.1.0.aarch64-linux-gnu-cxx03.tar.gz"
[[ICU]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e78b3d03c33448cdc9f24f38f66875f97e339f05"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "1d30d23da2550bd048ddbad5b2693979d2bcfc42bf1e6f76f272dea09425fb37"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+0/ICU.v67.1.0.aarch64-linux-gnu-cxx11.tar.gz"
[[ICU]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2ab894466cb0e108e45be6803f825429632badee"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "233d3073a34d81600c25dfe12c9ec3982167825587078411bc801c17603fe9a4"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+0/ICU.v67.1.0.aarch64-linux-musl-cxx03.tar.gz"
[[ICU]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1dcb15efe88105e15a8a234b2ee71a8f9d54e871"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "0d446a1281800194211ad9cfcbdb52e65a4e115d46ea89800a1df91a764a5029"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+0/ICU.v67.1.0.aarch64-linux-musl-cxx11.tar.gz"
[[ICU]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7b1f2bfb0cf2765dd963db4e424c4a8cb05f6233"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "816e571d2c99e01737d6c208ea081f2e5a8d15bda691f267d52cb4442b802d3a"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+0/ICU.v67.1.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ICU]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "de573eb705d2ff4059c44c4bf39aa3922a2c88c0"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "66aca331bde30105801243d2623548189167112511b2ff864583e1d5b406c846"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+0/ICU.v67.1.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ICU]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fe72c86a0ade02b22df57f15e31ec44dc9a26ec1"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "61e6735348632cab5161158ce19b5e4a4fc2c54a808ce4ab57720c80e4235e13"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+0/ICU.v67.1.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ICU]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "253dd80d17d89edb38725e5479e2816d51938af3"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "db000a15701bcd2bca6ecc3550731aaef945c33bd805f2af5901154c50d8add8"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+0/ICU.v67.1.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ICU]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9594ed4addde560f5e0e081bc42ccb2b78c710b3"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "6f40b013d2cca0ee1fc9add4e7192ea717d01e43d89062ef453a5e99844b28b8"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+0/ICU.v67.1.0.i686-linux-gnu-cxx03.tar.gz"
[[ICU]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b2abf5b5a60aeed9804e818f38b17cf824403b9e"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "0c0df3b07aade4e588dbfc9cd14bc327c536257ec4c4d27db8960facdc386068"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+0/ICU.v67.1.0.i686-linux-gnu-cxx11.tar.gz"
[[ICU]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c57ee35d99b70ab32e7da15f7c107935cbbc7cdc"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "925854690842bdfb52297729465283c6ce9d176fa5e2549331d8ee4323cef802"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+0/ICU.v67.1.0.i686-linux-musl-cxx03.tar.gz"
[[ICU]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e1ba16a20d1cef56c8446c38e108277185238407"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "75c99f91b15cb148e848a34c8525df1c9c9fbba78ca6f1104d77aa294b294566"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+0/ICU.v67.1.0.i686-linux-musl-cxx11.tar.gz"
[[ICU]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "36d630fb200defc435624a2aaab910d9dcdaf210"
os = "windows"

    [[ICU.download]]
    sha256 = "b9c6bb31bdc3facc4e118e22206464efe12066896c8be74313183806377e77be"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+0/ICU.v67.1.0.i686-w64-mingw32-cxx03.tar.gz"
[[ICU]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb6b2cff38b9ca34703c6a2732715111c8fd2d2a"
os = "windows"

    [[ICU.download]]
    sha256 = "b7366300ffa278876374c539c6dd1f96b40d2805c0465409e1dc0f135071346e"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+0/ICU.v67.1.0.i686-w64-mingw32-cxx11.tar.gz"
[[ICU]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "089dec997852822e73f287098b865fea74622fd0"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "1b993978614ddca65d5107859c7a159075faf0ea7b53d4f76c4ece0663a5f776"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+0/ICU.v67.1.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[ICU]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "71ad4c7c88502b9ae1c214e4ba283780c3d4f1f4"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "0c6b86cf0e839dcb6b47a9847e6b288ed7b41e5a185b455042d8b3f17495bf22"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+0/ICU.v67.1.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ICU]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6232514a5357c7cadb9f9f467f02089e7011345d"
os = "macos"

    [[ICU.download]]
    sha256 = "93a547d1835f7a556c9770d8a54a11180e7ee65c0a76854d48d9d3d893ba8651"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+0/ICU.v67.1.0.x86_64-apple-darwin14-cxx03.tar.gz"
[[ICU]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d1ec5f3f7b2b7c58eedc6f93f4a0361ca2587807"
os = "macos"

    [[ICU.download]]
    sha256 = "22d43865b5d8a3909ffb99fa82969ba9881456e67294151b5f7a7c2244a53abd"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+0/ICU.v67.1.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[ICU]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5f591a41be6ed1e28f4c20c077de2c8ba64aa49e"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "7b6aa39b8d4e43e70d80a092869bb10315d86d72ce57c64bc1564cffa808e820"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+0/ICU.v67.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[ICU]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "19dbc9e0f1763d5d421944474a173e29a16db247"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "13624c6894e916741d4a4ec664c2cb0145b44515b500dc2954e1f60ba64d23d1"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+0/ICU.v67.1.0.x86_64-linux-gnu-cxx11.tar.gz"
[[ICU]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "92ec4e7c398773c35f673e635d7b384aa0949edd"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "5469010a8ffdb48432301a7996671eaa33ab40ea4b0e79af7b6a91086d91a7d8"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+0/ICU.v67.1.0.x86_64-linux-musl-cxx03.tar.gz"
[[ICU]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "69ffa248c873669d12a24fce1badb0cc5b254d13"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "fff8c959fdadc9be28bc37c3b41d65e45498e5e9eb1e4b991c8caa0bda3f5826"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+0/ICU.v67.1.0.x86_64-linux-musl-cxx11.tar.gz"
[[ICU]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bdc82b691b002a127c540a108083f98344867e4d"
os = "freebsd"

    [[ICU.download]]
    sha256 = "dc5e5bd3fc09c3c2cce9071fb11bea7f1f64b12a6e0732e2c050c5b1b2856fbb"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+0/ICU.v67.1.0.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[ICU]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b3f0fef13f8bbb4fec166f3f8cc9ecfe98913c1b"
os = "freebsd"

    [[ICU.download]]
    sha256 = "b4eaba12831b724bbb961480ce4c071ec8c91d65e837d218860859c8fdb80b3b"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+0/ICU.v67.1.0.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[ICU]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "10c11d0dde26de10b414244676eacd09116c37ca"
os = "windows"

    [[ICU.download]]
    sha256 = "ede93d13d1273340e667c2265c50f03d1d536a71e8888547b14fd0deae55ae33"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+0/ICU.v67.1.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[ICU]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a91b23d96184c536deb64ccb463975f0a40817b7"
os = "windows"

    [[ICU.download]]
    sha256 = "1b9031ddc5e67083edea376dc35cb8f60defbd9db19951550fe3643e490f4d18"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v67.1.0+0/ICU.v67.1.0.x86_64-w64-mingw32-cxx11.tar.gz"
