[[ICU]]
arch = "aarch64"
git-tree-sha1 = "f4544fd4c1a2a46f8e336c0d946fe940ebea6229"
os = "macos"

    [[ICU.download]]
    sha256 = "6537e76a8d36488fbe40a589505f7a7546bd202a511b278bff2f292ee047d741"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v74.1.0+0/ICU.v74.1.0.aarch64-apple-darwin.tar.gz"
[[ICU]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ff66d56af6b29a23751fd7f03a4b573a20bd15fb"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "7d446a84facf24fcbee0f11e0b5c64320c0dd36ff98799915be5ae78a811df06"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v74.1.0+0/ICU.v74.1.0.aarch64-linux-gnu-cxx03.tar.gz"
[[ICU]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d9346edd0cb2e79321b7c72fd06263ecdda99ae8"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "20ff3c19b11d48af005d688fa5c2736159c2be608fa86a879198c8369f05be63"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v74.1.0+0/ICU.v74.1.0.aarch64-linux-gnu-cxx11.tar.gz"
[[ICU]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "086b83422b0a9ea2fa6307a2af5c053afa526258"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "fa389d06cd1253d60d6d7c4560a99102d0658d05076780ab390c8f6203e847d4"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v74.1.0+0/ICU.v74.1.0.aarch64-linux-musl-cxx03.tar.gz"
[[ICU]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "839cdb958951030c3d22e22106b1c4eb8558fc35"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "c814f8d792a7740a14ac1b272377edd9dc073f68669fdd1b3d776a64b7cfe28b"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v74.1.0+0/ICU.v74.1.0.aarch64-linux-musl-cxx11.tar.gz"
[[ICU]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dda4bd7f349b60badd9446a094ba04ea40b781b8"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "7cd26f38d4baaf1704db64efb888aeaca142bf7e2d5edc0d00c8fea8abd18316"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v74.1.0+0/ICU.v74.1.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ICU]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed50d768bb1bb153c66af9132c59dd4dd902b4d2"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "45f8523627f81dec41f2f9c64c24bf0dfc8a30400182590b2cc850681577080e"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v74.1.0+0/ICU.v74.1.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ICU]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b06871f620ef12777faec8b32e4c0b174e2afc0f"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "d6d7ca707696b18b619fe54a5c5b8ca7513388284f4dc434c90f81da7a649d18"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v74.1.0+0/ICU.v74.1.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ICU]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "03d63123c00dfb23bc315310bddbb7c4119c6f54"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "84e4ff2eea07d49b4691856f9bec1a5912b2bdcff7632db77115d73d745f80fb"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v74.1.0+0/ICU.v74.1.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ICU]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c9667313676a24d6ff4a636ca3fdc35ca1f90c29"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "faaeb8d91cb2a5031553bdff84bba0d8f400447d844653425e10ba142ebd218b"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v74.1.0+0/ICU.v74.1.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ICU]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "28e8b5560683a49d8d5e6a4af73dd04dabb7c59f"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "2b7a02da26d707435c0adaad1fe3ebab227b98557a9e111ae958096d90b10f11"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v74.1.0+0/ICU.v74.1.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ICU]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "334c5ee504755e04fccb651eafaafacba9adca05"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "f6b0fda3c8684066db7dc35ee76a562e5a63493e4a9d77538b15f28809b2f66e"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v74.1.0+0/ICU.v74.1.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ICU]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eca8e22b33fd339e7b07ee2ee1e30e3ff9d95327"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "d4ad77c49f2de893ddf8c163106f709e73ff232c3281151325598780f011099f"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v74.1.0+0/ICU.v74.1.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ICU]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "71b383e3c4c80507d71faf9e110b809528e5683c"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "01b361fd44fab521e31fbeab97e6cfbecb5f245c94289f69d24853372b5379dd"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v74.1.0+0/ICU.v74.1.0.i686-linux-gnu-cxx03.tar.gz"
[[ICU]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2162ac698a669187f17c88dbf4eb3187f5095a4b"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "4f0764525a2474fe74bc1e45a022212de0a42435bf2c60ca60d8630b7eee9bd0"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v74.1.0+0/ICU.v74.1.0.i686-linux-gnu-cxx11.tar.gz"
[[ICU]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4db3152c76c08cb9f5cf7022d38c14012d853106"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "bfbb7d1d0eaea919e54a7eba772df5e18e2572141591ef668cb69703ae57660e"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v74.1.0+0/ICU.v74.1.0.i686-linux-musl-cxx03.tar.gz"
[[ICU]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3530fe49e55d2201e68f2c605a455f451ecf7db1"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "e2fcca3a0f3ddb304c5ee09fb6fc5b4a502fa0da0446b255cb6a8bb06d8bd24e"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v74.1.0+0/ICU.v74.1.0.i686-linux-musl-cxx11.tar.gz"
[[ICU]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a85588dcfb7f595c28a47160fdcee9a00727cefb"
os = "windows"

    [[ICU.download]]
    sha256 = "48b68fb24ebd858d254d1ca9b58638f25d8aef9d3929c458c5b1683e7ce4b4b1"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v74.1.0+0/ICU.v74.1.0.i686-w64-mingw32-cxx03.tar.gz"
[[ICU]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e91a1135262aa4f338ccb8585a656aa4231edca0"
os = "windows"

    [[ICU.download]]
    sha256 = "17725dc41d784a527268446c50ae05570aa6d52af58b23cb5734009e0ab0ddfb"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v74.1.0+0/ICU.v74.1.0.i686-w64-mingw32-cxx11.tar.gz"
[[ICU]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "05fec5e3b8f16d577c40f397666b3f634970dcbb"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "a4c8cd48894357c82a5e9a3eb178e7058a851bb24a0b6894da54b48f13d6d809"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v74.1.0+0/ICU.v74.1.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[ICU]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "19805e13c1970b21e3277dfe67498c0f0186be6c"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "98627b247f685dcf2f7c80c8c9429700baf560920c52c36b0491281efbddd7e7"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v74.1.0+0/ICU.v74.1.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ICU]]
arch = "x86_64"
git-tree-sha1 = "ec4d74751e565fe92522a7b556175e471d446524"
os = "macos"

    [[ICU.download]]
    sha256 = "8d53f54fc4799f314f2c483203d620cc336b18fd0f7f263d526374b597b8508f"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v74.1.0+0/ICU.v74.1.0.x86_64-apple-darwin.tar.gz"
[[ICU]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "66d1937b2692b001dfad34616d078bf04a0eada9"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "346e05d8cb6b3be97a2c5b3c7f35e9fbfc594efa5244a46e35923c08d3cfc6d5"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v74.1.0+0/ICU.v74.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[ICU]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f4132e82705a1eaa38f1eb23df661839d399f3a"
libc = "glibc"
os = "linux"

    [[ICU.download]]
    sha256 = "a56fde1fd86e43c20afd7eb0d12469138a26f36e69d37095574045d714d84002"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v74.1.0+0/ICU.v74.1.0.x86_64-linux-gnu-cxx11.tar.gz"
[[ICU]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0474a2691bf31287dd6e86bd46218a2bdd1648d4"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "346f0d5f6251dc20eea3d1ecbb83e4da282bfd63449254b90ff78d888c3ad140"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v74.1.0+0/ICU.v74.1.0.x86_64-linux-musl-cxx03.tar.gz"
[[ICU]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "82e4f5e3f965aba05217d0bc9bc1810853130b2f"
libc = "musl"
os = "linux"

    [[ICU.download]]
    sha256 = "eee65f51a2d4fcdab3d1f607c1508bc0cc7e8f4b667c739d42bdc29de44523cd"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v74.1.0+0/ICU.v74.1.0.x86_64-linux-musl-cxx11.tar.gz"
[[ICU]]
arch = "x86_64"
git-tree-sha1 = "a0360ff63eb2e11846175bfcbcc86754dd43b3aa"
os = "freebsd"

    [[ICU.download]]
    sha256 = "04cf8452c7d9dc12eacffc76b96f61ea1a15fac09762826d4eccf4f4b671d681"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v74.1.0+0/ICU.v74.1.0.x86_64-unknown-freebsd.tar.gz"
[[ICU]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f959c20e561a0628f310cd8621d93ab673b0d3d3"
os = "windows"

    [[ICU.download]]
    sha256 = "857852c36b3ff8b8ea4f27be47b586c2aaee7704b091c24ba5a1f3443fec87ed"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v74.1.0+0/ICU.v74.1.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[ICU]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e1e5d6f032b0d404ee67dd012ff911604028eb1d"
os = "windows"

    [[ICU.download]]
    sha256 = "c2f20622470fa4ea2e0cfc2d68b0dafbf78c639841e7be9fd5cfd46635d9431c"
    url = "https://github.com/JuliaBinaryWrappers/ICU_jll.jl/releases/download/ICU-v74.1.0+0/ICU.v74.1.0.x86_64-w64-mingw32-cxx11.tar.gz"
