# Autogenerated wrapper script for ICU_jll for i686-w64-mingw32-cxx11
export libicudata, libicui18n, libicuio, libicutest, libicutu, libicuuc

JLLWrappers.@generate_wrapper_header("ICU")
JLLWrappers.@declare_library_product(libicudata, "icudt67.dll")
JLLWrappers.@declare_library_product(libicui18n, "icuin67.dll")
JLLWrappers.@declare_library_product(libicuio, "icuio67.dll")
JLLWrappers.@declare_library_product(libicutest, "icutest67.dll")
JLLWrappers.@declare_library_product(libicutu, "icutu67.dll")
JLLWrappers.@declare_library_product(libicuuc, "icuuc67.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libicudata,
        "bin\\icudt67.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libicui18n,
        "bin\\icuin67.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libicuio,
        "bin\\icuio67.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libicutest,
        "bin\\icutest67.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libicutu,
        "bin\\icutu67.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libicuuc,
        "bin\\icuuc67.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
