# Autogenerated wrapper script for ICU_jll for x86_64-w64-mingw32-cxx11
export libicudata, libicui18n, libicuio, libicutest, libicutu, libicuuc

JLLWrappers.@generate_wrapper_header("ICU")
JLLWrappers.@declare_library_product(libicudata, "icudt76.dll")
JLLWrappers.@declare_library_product(libicui18n, "icuin76.dll")
JLLWrappers.@declare_library_product(libicuio, "icuio76.dll")
JLLWrappers.@declare_library_product(libicutest, "icutest76.dll")
JLLWrappers.@declare_library_product(libicutu, "icutu76.dll")
JLLWrappers.@declare_library_product(libicuuc, "icuuc76.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libicudata,
        "bin\\icudt76.dll",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libicui18n,
        "bin\\icuin76.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libicuio,
        "bin\\icuio76.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libicutest,
        "bin\\icutest76.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libicutu,
        "bin\\icutu76.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libicuuc,
        "bin\\icuuc76.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
