# Autogenerated wrapper script for ICU_jll for x86_64-w64-mingw32-cxx11
export libicudata, libicui18n, libicuio, libicutest, libicutu, libicuuc

JLLWrappers.@generate_wrapper_header("ICU")
JLLWrappers.@declare_library_product(libicudata, "icudt68.dll")
JLLWrappers.@declare_library_product(libicui18n, "icuin68.dll")
JLLWrappers.@declare_library_product(libicuio, "icuio68.dll")
JLLWrappers.@declare_library_product(libicutest, "icutest68.dll")
JLLWrappers.@declare_library_product(libicutu, "icutu68.dll")
JLLWrappers.@declare_library_product(libicuuc, "icuuc68.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libicudata,
        "bin\\icudt68.dll",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libicui18n,
        "bin\\icuin68.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libicuio,
        "bin\\icuio68.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libicutest,
        "bin\\icutest68.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libicutu,
        "bin\\icutu68.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libicuuc,
        "bin\\icuuc68.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
